LIME-915 - Creating Authenticate Call for crosscore V2
govuk-one-login/ipv-cri-fraud-api pull request #195
Opened 2024-01-09 20:51 UTC by ElliotMurphyGDS

2024-01-10 12:21 UTC, smsgds requested changes

2024-01-10 12:21 UTC, smsgds commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/TokenHttpRetryStatusConfig.java
> +        return FRAUD_HTTP_RETRYER_REQUEST_SEND_OK.withEndpointPrefix();
The TokenHttpRetryStatusConfig should be using something like TOKEN_CROSSCOREV2_HTTP_RETRYER_REQUEST_SEND_OK metrics

2024-01-10 12:21 UTC, smsgds commented on lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/metrics/ThirdPartyAPIEndpointMetric.java
> +    AUTHENTICATE_TOKEN_REQUEST_REUSING_CACHED_TOKEN(FRAUD_V1, "reusing_cached_token"),
We can't use FRAUD_V1 as this for CrossCore 1 metrics authenticate merrics and instead create a new prefix for the token of crosscore v2.

To split them up so we can graph them later we need something like this - 
e.g
`TOKEN_CROSSCOREV2_REQUEST_CREATED(CROSSCOREV2_TOKEN, REQUEST_CREATED)`

Then for authv2 and pepv2

`AUTHENTICATE_CROSSCOREV2_REQUEST_CREATED(CROSSCOREV2_AUTHENTICATE, REQUEST_CREATED)`
`PEPSANCTION_CROSSCOREV2_REQUEST_CREATED(CROSSCOREV2_PEPSANCTIONS, REQUEST_CREATED)`

2024-01-11 11:34 UTC, gds-jbentham commented on infrastructure/lambda/template.yaml
> +      TableName: !Sub "experian-token-${AWS::StackName}"
In the off chance we ever have another experian token could we make this crosscorev2-authenticate-token

2024-01-11 17:00 UTC, gds-jbentham commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/util/TokenRequestService.java
> +    private static final long MAX_ALLOWED_TOKEN_LIFETIME_SECONDS = 3600L;
I think this should be 30 mins rather than 60

2024-01-11 17:06 UTC, gds-jbentham commented on lib/src/main/java/uk/gov/di/ipv/cri/fraud/library/metrics/ThirdPartyAPIMetricEndpointPrefix.java
> +    PEP_V1,
We have a trailing comma here

2024-01-11 17:07 UTC, gds-jbentham commented on lambdas/fraudcheck/src/main/java/uk/gov/di/ipv/cri/fraud/api/service/FraudCheckConfigurationService.java
> +        this.tokenEndpoint = paramProvider.get(getParameterName("CrosscoreV2/tokenEndpoint"));
Have we added all these across the environments?

2024-01-18 10:22 UTC, smsgds approved these changes

2024-01-18 10:23 UTC, smsgds approved these changes

2024-01-18 10:40 UTC, merged